resolver: lts-9.14
# docker:
#   enable: true
#   repo: fpco/stack-full
# image:
#   containers:
#     - base: "fpco/stack-base" # see ./etc/docker/stack-base/Dockerfile
#       name: "fpco/stack-test"
packages:
- .
- location:
    git: https://github.com/haskell/hackage-security.git
    commit: 3297b0f3f4285cb30321baaa7b54e3d22e1f6bd7
  subdirs:
  - hackage-security
  extra-dep: true

extra-deps:
- bindings-uname-0.1
