resolver: lts-9.14
# docker:
#   enable: true
#   repo: fpco/stack-full
# image:
#   containers:
#     - base: "fpco/stack-base" # see ./etc/docker/stack-base/Dockerfile
#       name: "fpco/stack-test"
packages:
- .
- location:
    git: https://github.com/haskell/hackage-security.git
    commit: 3297b0f3f4285cb30321baaa7b54e3d22e1f6bd7
  subdirs:
  - hackage-security
  extra-dep: true

extra-deps:
- Cabal-2.0.1.0
- mintty-0.1.1
- bindings-uname-0.1
- path-0.6.1
- path-io-1.3.3
- extra-1.6
- hsc2hs-0.68.2
- hpack-0.20.0
- unliftio-0.2.1.0
- ansi-terminal-0.7.1.1
- ansi-wl-pprint-0.6.8.1
- smallcheck-1.1.3
